# Generated by Django 5.2.6 on 2025-09-24 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('total_permits_found', models.IntegerField(default=0)),
                ('total_project_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cities_processed', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('summary_report', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scraper_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('permit_id', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_address', models.CharField(max_length=500)),
                ('borough_area', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('project_description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contractor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contractor_license', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('architect_name', models.CharField(blank=True, max_length=200, null=True)),
                ('license_status', models.CharField(blank=True, max_length=50, null=True)),
                ('business_address', models.CharField(blank=True, max_length=500, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_source', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permits',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['city'], name='permits_city_a07ec9_idx'), models.Index(fields=['issue_date'], name='permits_issue_d_b42b27_idx'), models.Index(fields=['permit_id'], name='permits_permit__579540_idx'), models.Index(fields=['scraped_at'], name='permits_scraped_075575_idx')],
            },
        ),
    ]
