# Generated by Django 4.2.26 on 2025-11-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('files_count', models.IntegerField(default=0)),
                ('output_file', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'file_processor',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
